project:
  type: website
  output-dir: docs

website:
  favicon: logo.png
  title: "Data Ciphers Official Website"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Courseworks
        href: courses.qmd
        menu:
          - text: EMU430 Data Analytics
            href: emu430.qmd
          - text: EMU415 Database Management Systems
            href: emu415.qmd


            
    tools:
      - icon: github
        href: https://github.com/mer7kaplan/emu415-spring2024-team-data_ciphers
  sidebar:
    - title: "EMU430 Data Analytics"
      style: "docked"
      search: true
      contents:
        - emu430.qmd
        - emu430_1.qmd
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 415 - Spring 2024" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: flatly
    css: styles.css


editor: visual