project:
  type: website
  output-dir: docs

website:
  favicon: logo.png
  title: "Data Ciphers Official Website"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis
        href: analysis.qmd

            
    tools:
      - icon: github
        href: https://github.com/mer7kaplan/emu415-spring2024-team-data_ciphers

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 415 - Spring 2024" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: flatly
    css: styles.css


editor: visual